---
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_buildd
  build:
    commands:
      - mvn clean package
      - mv target/*.jar app.jar
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - app.jar
