version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_buildd
  build:
    commands:
      - mvn clean compile install
      - echo build
  post_build:
    commands:
      - echo post_build
artifacts:
  files:
    - target/emp-management-0.0.2-SNAPSHOT.jar
